# Generated by Django 5.2.7 on 2025-10-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name_plural': 'Movements'},
        ),
        migrations.AddField(
            model_name='movement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
